openapi: 3.1.0
info:
  title: Message API
  version: 1.0.0
  description: A simple API for sending and viewing messages containing a title and description.

servers:
  - url: https://api.example.com/v1

paths:
  /messages:
    get:
      summary: Get all messages
      operationId: getMessages
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      summary: Create a new message
      operationId: createMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageInput'
      responses:
        '201':
          description: The created message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          type: string
        description:
          type: string
    MessageInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
